# Generated by Django 4.2.20 on 2025-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=200)),
                ('date_completed', models.DateField()),
                ('short_description', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects_images/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
