# Generated by Django 5.0.1 on 2025-01-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0002_enquiryemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryemail',
            options={'verbose_name': 'EnquiryEmail Model', 'verbose_name_plural': 'EnquiryEmail Models'},
        ),
    ]
