# Generated by Django 4.2.20 on 2025-03-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0002_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Place',
            new_name='place',
        ),
    ]
