# Generated by Django 4.2.20 on 2025-03-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0003_rename_place_projects_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Project_name',
            new_name='project_name',
        ),
    ]
