# Generated by Django 5.0.1 on 2025-01-19 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0003_alter_enquiryemail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_category', to='couplers_app.projectscategory'),
        ),
    ]
