# Generated by Django 4.2.20 on 2025-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0004_rename_project_name_projects_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='place',
            field=models.CharField(max_length=40),
        ),
    ]
