# Generated by Django 5.0.1 on 2025-01-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0004_projectscategory_projects_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_open', models.TimeField()),
                ('office_close', models.TimeField()),
                ('address', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=12)),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
            ],
        ),
    ]
