# Generated by Django 5.0.1 on 2025-01-23 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0005_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('sub_heading', models.TextField()),
                ('main_content', models.TextField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('you_tube_link', 'You Tube Link')], max_length=225)),
                ('link', models.CharField(blank=True, max_length=225, null=True)),
                ('about_us_media', models.FileField(blank=True, null=True, upload_to='about_us_section/')),
            ],
        ),
        migrations.CreateModel(
            name='AdminAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('office_address', models.TextField(max_length=500)),
                ('mape_url', models.CharField(max_length=1000)),
                ('mobile_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 to 12 digits.', regex='^\\d{10,12}$')])),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdminBannerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(upload_to='banner_images/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminCounterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=225)),
                ('sub_heading', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLegalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=220)),
                ('document_type', models.CharField(choices=[('TandC', 'TandC'), ('PrivacyPolicy', 'PrivacyPolicy'), ('EULA', 'EULA')], max_length=20)),
                ('heading', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('module_image', models.ImageField(blank=True, null=True, upload_to='module_images/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.EmailField(max_length=225)),
                ('subject', models.CharField(blank=True, max_length=225, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_number', models.CharField(blank=True, max_length=225, null=True)),
                ('counter_text', models.CharField(blank=True, max_length=225, null=True)),
                ('counter_icon', models.FileField(blank=True, null=True, upload_to='counter_section/')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='counter_section/')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=225)),
                ('sub_heading', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('content', models.CharField(blank=True, max_length=225, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='counter_section/')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=225)),
                ('sub_heading', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('footer_logo', models.FileField(blank=True, null=True, upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=225)),
                ('sub_heading', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=225)),
                ('sub_heading', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('designation', models.CharField(blank=True, max_length=225, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='testimonial/')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProjectsCategory',
            new_name='AdminBannerText',
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RenameField(
            model_name='adminbannertext',
            old_name='description',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='adminbannertext',
            old_name='name',
            new_name='sub_heading',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
