# Generated by Django 5.0.1 on 2025-03-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0006_adminaboutussection_adminaddress_adminbannerslider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminproducts',
            name='description',
        ),
        migrations.AddField(
            model_name='adminproducts',
            name='description_for_detailed_page1',
            field=models.TextField(default='hwllo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminproducts',
            name='description_for_detailed_page2',
            field=models.TextField(default='hello', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminproducts',
            name='description_for_detailed_page3',
            field=models.TextField(default='j3llo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminproducts',
            name='product_heading',
            field=models.CharField(default='product', max_length=200),
            preserve_default=False,
        ),
    ]
