# Generated by Django 5.0.1 on 2025-03-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0007_remove_adminproducts_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminBannerSlider',
        ),
        migrations.AddField(
            model_name='adminbannertext',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='banner_images/'),
        ),
    ]
