# Generated by Django 4.2.20 on 2025-03-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplers_app', '0007_alter_adminteam_options_adminteam_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminteam',
            name='designation',
            field=models.CharField(max_length=30),
        ),
    ]
